version: '3.8'

services:

  # Development
  server:
    image: nginx:1.20.1-alpine
    ports:
      - '8000:80'
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  # Production
  # server:
  #   build:
  #     # The context defines the base folder of the commands inside dockerfiles
  #     # Ex.: "COPY . ." copies the current context folder in the WORKDIR of the
  #     # container
  #     context: .
  #     dockerfile: ./dockerfiles/prod/nginx.dockerfile
  #   ports:
  #     - '8000:80'
  #   depends_on:
  #     - php
  #     - mysql
  
  # Development
  php:
    build:
      context: ./dockerfiles/dev
      dockerfile: php.dockerfile
    volumes:
      - ./app:/var/www/html

  # Production
  # php:
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/prod/php.dockerfile
    
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    
  # Development
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./app:/home/laravel/app
    
  # Development
  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/php.dockerfile
    volumes:
      - ./app:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']

  # Development
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./app:/var/www/html
