version: '3.8'
services:
  server:
    image: nginx:1.20.1-alpine
    ports:
      - '8000:80'
    volumes:
      - ./app:/var/www/html
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conft:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./app:/var/www/html
    # No ports are needed since PHP is "invisible" from the host machine
    # and it just gets called internally by NGINX
    # ports:
      # - '3000:9000'
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./app:/home/laravel/app
  # artisan:
  # npm:
