version: '3.8'

services:

  mongodb:
    image: 'mongo:4.4.6-bionic'
    volumes:
      - mern-db:/data/db
    env_file:
      - ./env/mongodb.env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: foobar
    #   MONGO_INITDB_ROOT_PASSWORD: foobar

    #   # Alternative 1
    #   # - MONGO_INITDB_ROOT_USERNAME=foobar
    #   # - MONGO_INITDB_ROOT_PASSWORD=foobar

    # Docker Compose creates a network automatically for containers running
    # inside it, but you can specify a network explicitly like this
    # networks:
    #   - mern-net

  backend:
    # Build an image instead of using an existing official one
    build: ./backend
    # # Alternative
    # build:
    #   context: ./backend
    #   # Useful when the dockerfile has a different name
    #   # Ex.: "Dockerfile-dev"
    #   # dockerfile: Dockerfile
    #   args:
    #     myarg: 1
    ports:
      - '8080:80'
    volumes:
      - mern-logs:/app/storage/logs # This is a named volume
      - ./backend:/app # This is a bind mount
      - /app/node_modules # This is an anonymous volume
    env_file:
      - ./env/backend.env
    # Defers container running after the listed dependencies
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    # interactive mode (keep STDIN open)
    stdin_open: true
    # Terminal
    tty: true
    # If you want to force some container name
    # container_name: frontend-app
    depends_on:
      - backend

# This lists all named volumes
volumes:
  mern-db:
  mern-logs:
